### ISSUE TITLE
Chroma 4x4 prediction

### ISSUE THREAD

**Issue by felixf3** [AOMediaCodec/av1-spec#106]
From 6.9.29 Compute Prediction Semantics:  "Normally, a single prediction is performed for the entire chroma residual block based on the mode info of the bottom right luma block."

Now, in 5.9.4 Decode Block Syntax, HasChroma is non-zero only for the bottom-right luma block with odd MiRow and/or MiCol.

Then, in 5.9.32 Compute Prediction Syntax, the outer-most for loop has plane > 0 only for odd MiRow and/or MiCol because HasChroma > 0 in these cases only. 

So, for odd MiRow and/or MiCol, 
                                             candRow = (MiRow >> subY) << subY
                                             candCol = (MiCol >> subX) << subX

Therefore,  candRow, candCol point to the mode information of the TOP LEFT luma block.

This contradicts the quoted statement from 6.9.29: "... mode info of the BOTTOM RIGHT...". 

Please clarify.

**Comment by peterderivaz** [comment]
A single prediction based on the bottom right block is done for small blocks if SomeUseIntra is equal to 1.

When SomeUseIntra is equal to 1, the candidate location is adjusted to the bottom right block by the following code in 5.9.32:

if ( someUseIntra ) { 
  predW = num4x4W * 4 
  predH = num4x4H * 4 
  candRow = MiRow 
  candCol = MiCol 
}

**Comment by felixf3** [comment]
Thanks for the clarification. Perhaps, the word "normally" in the spec should be replaced with "if SomeUseIntra = 1". It was not obvious to me what "normal" is. To be fair, the next sentence begins with "however", so its opposite is presumably normal. But, since "normally" is somewhat vague, I suggest that it be replaced.

On a related note, if someUseIntra = 0, then in which cases do the  nested for loops containing Predict_Inter() iterate more than once?

Specifically, this quantity, 
             predH = Block_Height[ MiSize ] >> subY
                         = 4 * Num_4x4_Blocks_High[ MiSize ] >> subY. 
seems to be the same as this one
            num4x4H * 4 = 4 * Num_4x4_Blocks_High[ planeSz ]
                                    = 4 * Num_4x4_Blocks_High[get_plane_residual_size( MiSize, plane )]

So, shouldn't the Predict_Inter() always iterate only once ?

**Comment by peterderivaz** [comment]
Predict_inter can iterate more than once if using 4x4, 4x8, 8x4 block sizes (for certain cases of subsampling).

For example, if MiSize is 4x4 and we are in 4:2:0 subsampling and plane is equal to 1, then get_plane_residual_size will return 8x8.

**Comment by felixf3** [comment]
With the conditions in your example, get_plane_residual_size(4x4, 1) evaluates subx = suby = 1 and then Subsampled_size[4x4][1][1] = 4x4. 

I don't see how you obtained 8x8.

**Comment by felixf3** [comment]
Assuming that the the 8x8 in your example is a typo, then we have:
     planeSz = get_plane_residual_size( 4x4, 1 ) = 4x4
     num4x4H = Num_4x4_Blocks_High[ 4x4 ] = 1
     predH = Block_Height[ 4x4 ] >> 1 = 2

Then this for loop
     for( y = 0; y < num4x4H * 4; y += predH ) {
evaluates to      
     for( y = 0; y < 4; y += 2 ) {
and does indeed iterate more than once. 

If my understanding above is correct, then this note in 6.9.29 Compute Prediction Semantics is confusing:
"The chroma residual block size is always at least 4 in width and height ... special case is triggered and inter prediction is done using a smaller block size for each of the corresponding luma blocks."

Why is the special case only for the corresponding luma blocks?

From the above example, the special case seems to be for the corresponding chroma blocks.

Please clarify.

**Comment by peterderivaz** [comment]
Your understanding is correct.

The point it is trying to get across is that a chroma prediction needs to be done for each of the luma blocks that correspond to the same area.

So if the chroma residual block corresponds to two 8x4 luma blocks, then two chroma predictions will be done, each of size 4x2, one for each of the luma blocks.

**Comment by felixf3** [comment]
I see. 

Perhaps adding the adjective chroma may help: "inter prediction is done using the smaller chroma block size that corresponds to each of the luma blocks."  

The current wording in the spec, "smaller block size for each of the corresponding luma blocks" implies that the smaller blocks are luma blocks. This was really confusing to me.

I suggest a clarification as above.

**Comment by peterderivaz** [comment]
Thanks, I think your suggesting wording is a good improvement and I have added it to the spec.
