### ISSUE TITLE
Self guided parameter w1

### ISSUE THREAD

**Issue by olahugosson** [AOMediaCodec/av1-spec#109]
Hi Peter,

In section "7.16.2 Self Guided Filter Process" I'm wondering if 

       v = w1 * u

should rather be

       v = w2 * u

Regards
/Ola Hugosson

**Comment by peterderivaz** [comment]
Thanks, I've pushed a fix (note I think a different weight needs to be fixed).

(In my local version this was actually already correct, but I had forgotten to push the change back to the specification - many thanks for the reminder!)
