### ISSUE TITLE
Upscaling process

### ISSUE THREAD

**Issue by dkhe** [AOMediaCodec/av1-spec#112]
IN Section 7.16, the following line is used to compute pixel position in coding resolution (downscaled). 

srcX = -(1 << SUPERRES_SCALE_BITS) + initialSubpelX + x*stepX

Checking against the code, i could not seem to locate the corresponding part to -(1 << SUPERRES_SCALE_BITS), which in some cases makes srcX negative.

**Comment by peterderivaz** [comment]
See line 629 of av1/common/resize.c

    av1_convolve_horiz_rs(input - 1, in_stride, output, out_stride, width2,

The input to superres is (input-1) which uses pointer arithmetic to offset the src locations. 

In the specification we avoid pointer arithmetic,
so instead the offset is encoded as  -(1 << SUPERRES_SCALE_BITS).

**Comment by dkhe** [comment]
Right. Thanks. 

In that regard, would it not be the same to move the offset of 1 to the place where srcXPx is used (see below)?
 ```
            srcX = initialSubpelX + x*stepX
            srcXPx = (srcX >> SUPERRES_SCALE_BITS)
            srcXSubpel = (srcX & SUPERRES_SCALE_MASK) >> SUPERRES_EXTRA_BITS
            sum = 0
            for (k = 0; k < SUPERRES_FILTER_TAPS; k++) {
                sampleX = Clip3(minX, maxX, srcXPx + (k - SUPERRES_FILTER_OFFSET -1))
                px = frame[plane][y][sampleX]
                sum += px * Upscale_Filter[srcXSubpel][k]
            }
```

**Comment by dkhe** [comment]
Wrong button pressed above.

**Comment by peterderivaz** [comment]
Yes, that should be equivalent so you are free to implement it that way if you prefer.

The reason it is expressed the current way is so that srcXPx represents the position in the source image that should be sampled (with SUPERRES_EXTRA_BITS of fractional precision).

For example if srcXPx is equal to 0, then the output will be equal to frame[plane][y][x].

**Comment by dkhe** [comment]
Thanks for confirming.
