### ISSUE TITLE
Bitstream format terminology clarification 

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#115]
- The Abstract/Scope say
> This document defines the bitstream format 

- "bitstream" is only defined as:
>The sequence of bits generated by encoding a sequence of frames.

- "AV1 bitstream" is not defined 
- "bitstream format" is not defined 

- The current title for Annex B is:
> Annex B: Nominal bitstream interchange format

- The titles of B.1 and B.2 are:
> Bitstream syntax
> Bitstream semantics

Overall, this is misleading people into thinking that THE recommended format for AV1 is Annex B.

I would suggest:
- Adding a top-level section to the spec or as a high-level subsection of one of the existing sections, entitled "low overhead bitstream format", with the following content:
> This specification defines a low-overhead bitstream format as a sequence of the OBU syntactical elements defined in Section 5. When using this format, the `obu_has_size_field` may be used to enable parsers to skip OBUs without having to parse them. For applications requiring a format where it is easier to skip through frames or temporal units, a length-delimited bitstream format is defined in Annex B. Derived specifications, such as container formats enabling storage of AV1 videos together with audio or subtitles should indicate which of these formats they rely on.

- renaming Annex B to "Annex B: length-delimited bitstream format"
- Replace the overview as follows:
> Section 5 defines the syntax for OBUs. Section XXX defines the low-overhead bitstream format. This annex defines a length-delimited format for packing OBUs into a format that enables skipping through temporal units and frames more easily.

- Rename B1 and B2 to 
> Length-delimited bitstream syntax
> Length-delimited bitstream semantics

- Change the Abstract and Scope to use "bitstream formats" (plural)

**Comment by peterderivaz** [comment]
Thanks, I think this makes things much clearer.

Gary Sullivan had also pointed out similar shortcomings (the nominal bitstream interchange format was his suggested title but his main concern was the same as yours - namely that the old name was misleading) and he wanted it to be clear that OBUs may be put into other bitstream formats.

Therefore I have left in the sentence "Other methods of packing OBUs into a bitstream format are also allowed." 

Note it is not entirely clear whether this is intended.  His comment made it clear that at least one other method of packing is allowed.  However, now that your changes have explicitly defined an alternative format, it is not clear whether even more methods should be allowed or not.  Perhaps raise the issue in a call or on the email list if you think more discussion is required?

**Comment by cconcolato** [comment]
Changes in https://github.com/AOMediaCodec/av1-spec/commit/eb95aa111842a98a059ea575a330b84d87f9473f look good to me.
