### ISSUE TITLE
Description of OperatingPointIdc

### ISSUE THREAD

**Issue by soo-chul-han** [AOMediaCodec/av1-spec#116]
In 6.4, the following statement is found:

It is a requirement of bitstream conformance that if OperatingPointIdc is equal to 0, then obu_extension_flag is equal to 0.

Perhaps it would be clearer to add "for all OBUs that follow the sequence header OBU from which the OperatingPointIdc was derived from, until the next sequence header"  (to emphasize that the  requirement is valid following the zero OperatingPointIdc, and that OperatingPointIdc COULD change when a new sequence header is received)

I'm not sure my wording is 100% best wording, but I hope you get what I'm trying to convey

**Comment by peterderivaz** [comment]
Thanks
