### ISSUE TITLE
Warp valid constraints

### ISSUE THREAD

**Issue by felixf3** [AOMediaCodec/av1-spec#117]
In Section 7.11.3.6 (Setup Shear Process), warpValid is determined based on alpha0, beta0, gamma0 and delta0. 

Then these four variables are rounded to alpha, beta, gamma, delta with this type of code: 
alpha = Round2Signed( alpha0, WARP_PARAM_REDUCE_BITS ) << WARP_PARAM_REDUCE_BITS

This type of rounding could make alpha larger than alpha0 if the rounding is upward.

If so, then it is possible for warpValid to be true for alpha0, beta0, gamma0 and delta0, but false for alpha, beta, gamma, delta. 

The purpose of the warpValid constraints is to ensure that offs (in block warp process) is in the range 0 to 192 (corresponding to -1 to 2 in the 1/64-sample space). 

So due to the rounding of these variables, is it possible that offs could exceed the 0 to 192 range?

If so, shouldn't we determine warpValid using alpha, beta, gamma, delta instead of alpha0, beta0, gamma0, delta0?

**Comment by peterderivaz** [comment]
I believe the code matches the spec, so this is probably better posted as a code bug on the AOM bug tracker:

https://bugs.chromium.org/p/aomedia/issues/list

**Comment by peterderivaz** [comment]
The code has now been updated according to your suggestion, and I have updated the specification to match.
