### ISSUE TITLE
terms for Transform block

### ISSUE THREAD

**Issue by brayden-cnm** [AOMediaCodec/av1-spec#118]
Transform block is defined as below. I am not sure but I think transform block might be a square or rectangular like as Block. Would you please check this ?

> 2. Terms and definitions
> Transform block
> A square transform coefficient matrix, used as input to the inverse transform process.
> 

I have a simple question related to Quant. 
In the case of HEVC, we can easily know the maximum bit width for the quantized coefficients as below. 

> It is a requirement of bitstream conformance that the value of coeff_abs_level_remaining[ n ] shall be constrained such that the corresponding value of TransCoeffLevel[ x0 ][ y0 ][ cIdx ][ xC ][ yC ] is in the range of CoeffMinY to CoeffMaxY, inclusive, for cIdx equal to 0 and in the range of CoeffMinC to CoeffMaxC, inclusive, for cIdx not equal to 0.

However, We can't find it easily in the case of AV1 spec. Of course, AV1 spec. uses the bit and operator with 0xFFFFF. (We can know that maximum bit width is 20. but this will be various according to the input bit depth)
`
Quant[ pos ] = Quant[ pos ] & 0xFFFFF
`

From the AV1 reference code, I can see comments as below. Can I know the max and min value of the quantized coefficients according to the input bit depth? (quantized coefficients means that output of the entropy decoder and input of the inverse quantization block.)

```
      // Bitmasking to clamp level to valid range:
      //   The valid range for 8/10/12 bit vdieo is at most 14/16/18 bit
      level &= 0xfffff;
```

**Comment by peterderivaz** [comment]
Thanks, I've changed the terms for transform block in the commit above.

For the coefficients, the maximum bit width is 20 for all bit depths.

For real world content, I believe the expected bit widths are as described in the comment, but conformant decoders are nevertheless required to support the full range for all bit depths.

(There was some discussion about making the bit width depend on the bit depth, but this was rejected in favour of keeping the coefficient processing the same for different bit depths.)

**Comment by brayden-cnm** [comment]
Thanks.
