### ISSUE TITLE
su(n) definition simplification

### ISSUE THREAD

**Issue by eleft** [AOMediaCodec/av1-spec#12]
In section 4.9.4, the su(n) definition uses:

```if (value & signBit)
  value = value - 2 * signBit
````

You either keep the 'if' and keep it as \
```value = value - 2``` 

Or delete the 'if' and keep it as:
```value = value - 2 * signBit```

The text is not in error, it just has unnecessary computations.

**Comment by peterderivaz** [comment]
I am not sure I quite understand, I think both these changes would change the normative behaviour?

FIRST SIMPLIFICATION
-------------------------

Suppose n is 7, value is 0x81.

signBit will be equal to 0x80.

I believe the current spec will sign extend value to something like 0xff81 (assuming for the sake of argument that the return value type is int16_t).

If I use the first simplification I think I would end up with 0x7f (value - 2).

SECOND SIMPLIFICATION
----------------------------

Suppose n is 7, value is 0x01.

signBit will be equal to 0x80.

I believe the current spec will zero extend value to 0x0001 (assuming for the sake of argument that the return value type is int16_t).

If I use the second simplification I think I would end up with 0xff01.

**Comment by peterderivaz** [comment]
Ah, I think I understand the confusion.

signBit is a binary number with a 1 in the bit corresponding to the sign bit.

I think you interpreted it as being equal to (value >> 1) & 1, i.e. the value of the bit corresponding to the sign?

Is there a different name I could give it that would be less confusing do you think?  Perhaps signMask?

**Comment by eleft** [comment]
Sorry for the false alarm, I should have been more careful! Yes, I think 'signMask' will warn for what to look for! Thanks.

**Comment by peterderivaz** [comment]
Fixed in https://github.com/AOMediaCodec/av1-spec/commit/318877d683f6a6b341611ac7d1a26168c7b7422a
