### ISSUE TITLE
Single reference restriction on sub8x8 MI block

### ISSUE THREAD

**Issue by petethecat** [AOMediaCodec/av1-spec#121]
In the code decodeframe.c, function dec_build_inter_predictors(): if (sub8x8_inter), assert(!is_compound). 

I don't see where the spec restricts it from being compound. I see Section 5.11.25 of the spec, but it can still be skip_mode and therefore compound prediction, right?

Thanks.

**Comment by peterderivaz** [comment]
In read_skip_mode: http://av1-spec.argondesign.com/av1-spec/av1-spec.html#skip-mode-syntax
if the width or height is less than 8, skip_mode is forced to zero.

sub8x8_inter can only be 1 when the width or height is less than 8. (see line 837 of reconinter.c)

Therefore I believe it is impossible to have skip_mode equal to 1 and sub8x8_inter equal to 1 at the same time.
