### ISSUE TITLE
Clarification on ReadDeltas

### ISSUE THREAD

**Issue by dominicsymes** [AOMediaCodec/av1-spec#124]
There is a comment in section 6.10.2 of the specification:

"ReadDeltas specifies whether the current block may read delta values for the quantizer index and loop filter. Delta values for the quantizer index and loop filter are only read on the first non-skipped block of a superblock."

Looking at the syntax tables 5.11.12 and 5.11.13,  it appears that the values are read for the first block of a superblock unless the block is skipped and the block is the size of the whole superblock:

"if ( MiSize == sbSize && skip ) return"

So my understanding is that if a superblock starts with a skipped block which is not the whole superblock then ReadDeltas will apply - and so the comment on ReadDeltas seems wrong.

**Comment by peterderivaz** [comment]
Good point, I have reworded this section in the commit above.

**Comment by dominicsymes** [comment]
thanks
