### ISSUE TITLE
Clarification on TotalDisplayLumaSampleRate

### ISSUE THREAD

**Issue by dominicsymes** [AOMediaCodec/av1-spec#130]
In section A.3: TotalDisplayLumaSampleRate is defined as: "the luma sample rate (i.e. based on width * height of the output luma plane) for all output frames with the flag show_frame equal to 1 and frames referenced in frame headers with show_existing_frame = 1 for the scalability layer that conforms to the level indicated for this layer". It seems to me that the expression "frames referenced in frame headers" could be read two ways - that you count such frames once - or that you count such frames for each reference (now that we allow multiple references). I assume it should be for each reference (since the frames is displayed multiple times  if references multiple times). Just wondering if it would be possible to clarify the text.

**Comment by peterderivaz** [comment]
Good point, I am struggling to word this in a way that incorporates the new multiple reference feature - do you have a suggestion?

**Comment by dominicsymes** [comment]
Would it be useful to use similar wording to your updated TotalDecodedLumaSampleRate and make use of showCount?

For example: TotalDisplayLumaSampleRate is defined as the sum of the UpscaledWidth * FrameHeight * showCount of all frames that belong to the temporal unit that belongs to the operating point, divided by the time difference between the display time of the first frame of the current temporal unit and the display time of the first frame of the next temporal unit (if present).

**Comment by dominicsymes** [comment]
Thanks for clarification. I suppose TotalDecodedLumaSampleRate now needs changing giving the decision of the group yesterday that show_existing_frames is not counted in the decoding time.
