### ISSUE TITLE
Spec: redundant mapping of lr_type

### ISSUE THREAD

**Issue by chengchen-google** [AOMediaCodec/av1-spec#133]
The spec defines lr_type and maps is to FrameRestorationType:
FrameRestorationType[i] = Remap_Lr_Type[lr_type];

However, the libaom reference code doesn't implement lr_type, only FrameRestorationType is used.
The extra mapping seems redundant.

Propose to remove lr_type and use FrameRestorationType to keep it consistent with reference software.

**Comment by peterderivaz** [comment]
The libaom reference code reads lr_type using the following code:

  if (aom_rb_read_bit(rb)) {
      rsi->frame_restoration_type =
          aom_rb_read_bit(rb) ? RESTORE_SGRPROJ : RESTORE_WIENER;
    } else {
      rsi->frame_restoration_type =
          aom_rb_read_bit(rb) ? RESTORE_SWITCHABLE : RESTORE_NONE;
    }

this is reading three different 1 bit syntax elements and performing a mapping with code.

The spec simplifies this to reading one syntax element and doing the mapping with a table.

Overall this reduces the implementation from 7 lines in the code to 2 lines in the spec.

**Comment by chengchen-google** [comment]
Peter,

Thanks for the explanation. That makes sense.

Still, we can let the mapping from FrameRestorationType to lr_type be identical, and thus get rid of lr_type. I can submit a new patch to do that. But it would be a normative change. Do you prefer that? If not, I will only add a table in current reference code as spec, to make spec and reference code  consistent.

**Comment by peterderivaz** [comment]
I would have preferred your suggested change if it was made a few months ago, but now I think it is much too late to make this kind of normative change as it will delay the freeze.

In general the spec tries to provide an easier to understand explanation of the bitstream, while the code tries to provide an optimized implementation of the decoding process.  Therefore I don't think the code has to look the same as the spec provided the normative decoding behaviour is identical.
