### ISSUE TITLE
Unnecessary line in tile_info

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#140]
> maxTileHeightSb = sbRows >> minLog2TileRows

This line in tile_info, when uniform_tile_spacing_flag is true, is useless maxTileHeightSb is never used.

**Comment by peterderivaz** [comment]
Thanks, I agree this line is unnecessary.

I've created a pull request for this as I believe the 1.0 spec is meant to be frozen and I don't want to upset the freeze process.

Adrian/Lou, it is up to you if you want to merge this pull request or not.
