### ISSUE TITLE
loop_filter_ref_deltas order in "5.9.11. Loop filter params syntax"

### ISSUE THREAD

**Issue by wangf1978** [AOMediaCodec/av1-spec#151]
RefFrame[ 0 ] | Name of ref_frame
---------------|------------------------
0 | INTRA_FRAME
1 | LAST_FRAME
2 | LAST2_FRAME
3 | LAST3_FRAME
4 | GOLDEN_FRAME
5 | BWDREF_FRAME
6 | ALTREF2_FRAME
7 | ALTREF_FRAME

But the order in "5.9.11. Loop filter params syntax", it does not follow it

loop_filter_params( ) { |Type
------------------------|----
loop_filter_ref_deltas[ INTRA_FRAME ] = 1|
loop_filter_ref_deltas[ LAST_FRAME ] = 0|
loop_filter_ref_deltas[ LAST2_FRAME ] = 0|
loop_filter_ref_deltas[ LAST3_FRAME ] = 0|
loop_filter_ref_deltas[ BWDREF_FRAME ] = 0|
loop_filter_ref_deltas[ GOLDEN_FRAME ] = -1|
loop_filter_ref_deltas[ ALTREF_FRAME ] = -1|
loop_filter_ref_deltas[ ALTREF2_FRAME ] = -1|

**Comment by peterderivaz** [comment]
The order in loop filter params is chosen to place the right hand sides in the natural order.  (The order of values within the enum is not considered to be significant.)

The reference code in common/entropymode.c also uses the same order as the specification (in av1_set_default_ref_deltas):

  ref_deltas[INTRA_FRAME] = 1;
  ref_deltas[LAST_FRAME] = 0;
  ref_deltas[LAST2_FRAME] = ref_deltas[LAST_FRAME];
  ref_deltas[LAST3_FRAME] = ref_deltas[LAST_FRAME];
  ref_deltas[BWDREF_FRAME] = ref_deltas[LAST_FRAME];
  ref_deltas[GOLDEN_FRAME] = -1;
  ref_deltas[ALTREF2_FRAME] = -1;
  ref_deltas[ALTREF_FRAME] = -1;
