### ISSUE TITLE
rounding for warp filtering

### ISSUE THREAD

**Issue by petethecat** [AOMediaCodec/av1-spec#153]
In AV1 spec 7.11.3.5, the rounding for warp filtering is 0, but in the code, the rounding is (1<<offset_bits_horiz) for horizontal filtering and (1 << offset_bits_vert) for vertical filtering. The related code is pasted as below:

In AV1 spec:
s = 0
for ( i3 = 0; i3 < 8; i3++ ) {
    s += Warped_Filters[ offs ][ i3 ] * ref[ plane ][ Clip3( 0, lastY, iy4 + i1 ) ][ Clip3( 0, lastX, ix4 + i2 - 3 + i3)]
}
intermediate[(i1 + 7)][(i2 + 4)] = Round2(s, InterRound0)

In the code warped_motion.c:
int32_t sum = 1 << offset_bits_horiz;
for (int m = 0; m < 8; ++m) {
    const int sample_x = clamp(ix + m, 0, width - 1);
    sum += ref[iy * stride + sample_x] * coeffs[m];
    }
sum = ROUND_POWER_OF_TWO(sum, reduce_bits_horiz);

**Comment by peterderivaz** [comment]
I believe both code and spec produce the same output.

The code use an extra offset to the values to reduce the dynamic range needed for intermediate values, but this is just an implementation detail so the specification does not do this.

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
