### ISSUE TITLE
conflict definition 'force_integer_mv' in uncompressed_header()

### ISSUE THREAD

**Issue by wangf1978** [AOMediaCodec/av1-spec#154]
Here is the specification definition in "5.9.2. Uncompressed header syntax" of av1-spec-v1.0.0
```
if ( allow_screen_content_tools ) {
    if ( seq_force_integer_mv == SELECT_INTEGER_MV ) {
        force_integer_mv
    } else {
        force_integer_mv = seq_force_integer_mv
    }
} else {
    force_integer_mv = 0
}
if ( FrameIsIntra ) {
    force_integer_mv = 1
}
```
The last statement is weird
```
if ( FrameIsIntra ) {
    force_integer_mv = 1
}
```
and it conflicts with the official aom reference source code host in https://aomedia.googlesource.com/aom/, there is no implementation for it at all, not sure which is right.<br>
aom\av1\decoder\decodeframe.c
```
static int read_uncompressed_header(AV1Decoder *pbi,
                                    struct aom_read_bit_buffer *rb) {
  ......
  cm->disable_cdf_update = aom_rb_read_bit(rb);
  if (cm->seq_params.force_screen_content_tools == 2) {
    cm->allow_screen_content_tools = aom_rb_read_bit(rb);
  } else {
    cm->allow_screen_content_tools = cm->seq_params.force_screen_content_tools;
  }

  if (cm->allow_screen_content_tools) {
    if (cm->seq_params.force_integer_mv == 2) {
      cm->cur_frame_force_integer_mv = aom_rb_read_bit(rb);
    } else {
      cm->cur_frame_force_integer_mv = cm->seq_params.force_integer_mv;
    }
  } else {
    cm->cur_frame_force_integer_mv = 0;
  }

  cm->frame_refs_short_signaling = 0;
  int frame_size_override_flag = 0;
  cm->allow_intrabc = 0;
  cm->primary_ref_frame = PRIMARY_REF_NONE;
```

**Comment by peterderivaz** [comment]
The reference code has specific motion vector reading code for intra frames, while the specification uses a single, more general, motion vector reading specification.

This more general motion vector reading makes use of force_integer_mv so it needs to be set correctly.

Note that intra block copy uses motion vectors, but they must take integer values.

Therefore I believe both code and specification are correct.

**Comment by wangf1978** [comment]
If the current frame is an intra frame, but the field "allow_screen_content_tools" and " seq_force_integer_mv" cause to read one bit for force_integer_mv, there are 2 issues:

1.  Is it redundant to read this additional "force_integer_mv", because it is 1 whenever?
2.  If "force_integer_mv" is read from stream, and set to 0, but finally "force_integer_mv" is set to 1 because it is an intra frame, is it conflicted? 

(*) In this case, <br>
In Sequence_Header_OBU:<br>
seq_choose_screen_content_tools = 1
seq_force_screen_content_tools = SELECT_SCREEN_CONTENT_TOOLS
seq_choose_integer_mv = 1<br>
In FrameHeader OBU:<br>
allow_screen_content_tools = 1<br>
I didn't see the spec says it is not allowed, but it may cause this case mentioned.

**Comment by peterderivaz** [comment]
Q) Is it redundant to read this additional "force_integer_mv", because it is 1 whenever?
A) Yes, I believe it is redundant to read force_integer_mv for intra frames and the bit could be saved.

Q) If "force_integer_mv" is read from stream, and set to 0, but finally "force_integer_mv" is set to 1 because it is an intra frame, is it conflicted?
A) I believe this case is allowed and should behave the same in spec and code.  In both cases the behaviour should be as if force_integer_mv is set to 1.  In the spec, this behaviour is explicit.  In the code, this behaviour is implicit by the use of specialized motion vector reading code that assumes force_integer_mv is equal to 1.

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
