### ISSUE TITLE
Motion field estimation uses only backward reference types?

### ISSUE THREAD

**Issue by felixf3** [AOMediaCodec/av1-spec#157]
Section 7.9.2 (Projection Process) states "... projects the motion vectors from a whole reference frame (which will always be one of the backward reference types) ..."

However, in Section 7.9.1, the projected motion vectors can be from LAST_FRAME, BWDREF_FRAME, ALTREF2_FRAME, ALTREF_FRAME or LAST2_FRAME.

Of these, LAST_FRAME and LAST2_FRAME are forward reference types. 

So, the quoted statement in Section 7.9.2 is misleading. 

Please clarify.

**Comment by felixf3** [comment]
Perhaps the "always ... backward" clause refers to MfMvs storing motion vectors for backward predictions only in Section 7.19 (Motion field motion vector storage process) ?

**Comment by peterderivaz** [comment]
Good spot - the bracketed clause should be ignored, it is incorrect.  (When written there were two projection processes, one for forward and one for backward - but this is no longer the case.)

I have prepared a pull request that can be merged if the spec is unfrozen.

**Comment by peterderivaz** [comment]
Pull request is merged
