### ISSUE TITLE
issue for trailing bits 

### ISSUE THREAD

**Issue by totang** [AOMediaCodec/av1-spec#162]
From aom source code in function  av1_check_trailing_bits(...) ,
The nbBits (trailing bits  number) range is  0<nbBits<=8
but from the Av1 Spec ,nbBits = obu_size*8-payloadBits . 
It can great than 8 .In such case ,Zero bytes are trailing.

**Comment by peterderivaz** [comment]
I believe the reference code uses code spread over two locations to read/check the full trailing bits:

1. The code in av1_check_trailing_bits checks the first byte contains a 1 in the correct position
2. The code in lines 902 to 908 of obu.c checks the remaining bytes contain zeros

So I believe the reference code will also correctly decode streams containing trailing zero bytes.

**Comment by totang** [comment]
Yes ,for zero_byte. It can parsed as obu_type=0 which is reserved OBU.
From the "obu_size" field defined , it should treated  as trailing bytes ,not reserved OBU .
Spec is correct and reference code is some ambiguous 。

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required from the spec perspective - so I will close.

Please reopen if there is anything else to consider. And please open a bug against the reference code if necessary.
