### ISSUE TITLE
seq_profile table and Profile definition does not match

### ISSUE THREAD

**Issue by ChristianFeldmann** [AOMediaCodec/av1-spec#167]
In A.2 the definition is pretty clear:
seq_profile 0: Main Profile: 8-10bit 4:2:0
seq_profile 1: High Profile: 8-10bit 4:2:0 and 4:4:4
seq_profile 2: Professional Profile: 8-12 bit 4:2:0, 4:2:2 and 4:4:4

The table in 6.4.1, however, is very confusing:

| seq_profile | Bit depth | Monochrome support      | Chroma subsampling
| ----------- | --------- | ----------------------- | ------------------
| 0           | 8 or 10   | Yes                     | YUV 4:2:0
| 1           | 8 or 10   | No                      | YUV 4:4:4
| 2           | 8 or 10   | Yes                     | YUV 4:2:2
| 2           | 12        | Yes                     | YUV 4:2:0, YUV 4:2:2, YUV 4:4:4

Why are there two entries for seq_profile 2? Are there certain combinations not allowed? Shouldn't it be:

| seq_profile | Bit depth | Monochrome support      | Chroma subsampling
| ----------- | --------- | ----------------------- | ------------------
| 0           | 8 or 10   | Yes                     | YUV 4:2:0
| 1           | 8 or 10   | No                      | YUV 4:4:4 YUV 4:2:0
| 2           | 8 or 10 or 12   | Yes                     | YUV 4:2:0, YUV 4:2:2, YUV 4:4:4

**Comment by ccho111** [comment]
Yes, you're right that certain combination is not allowed for profile=2. You can check following syntax for subsampling_x and subsampling_y.

```
if ( BitDepth == 12 ) {
    subsampling_x
    if ( subsampling_x )
        subsampling_y
    else
        subsampling_y = 0
} else {
    subsampling_x = 1
    subsampling_y = 0
}
```

**Comment by ChristianFeldmann** [comment]
Ah so the table only lists the additionally supported modes (which makes perfect sense since this is how profiles work). Sorry about the dumb question.
