### ISSUE TITLE
Where I can find the spec for encoding process?

### ISSUE THREAD

**Issue by fangxiaoran** [AOMediaCodec/av1-spec#168]
Curious about the super resolution part in both encoding and decoding process. The one in decoding process is easier to understand, but in encoding process is not. So a spec is very needed.

For now, I have a question that why we need to save a up-scaled frame (large size) for reference in encoding process, cause in the beginning of encode_frame(), we still downscale the reference frames back to small size. Saving small scale references rather than large scale ones seems better, if my understanding is correct.

Actually, not very sure whether my question is proper in this repo. Appreciate your reply anyway.

**Comment by peterderivaz** [comment]
This question is probably more appropriate to be posted in the av1 discussion thread:

https://groups.google.com/a/aomedia.org/forum/#!forum/av1-discuss
