### ISSUE TITLE
Incorrect loop filter level minimum vals in 7.14.4?

### ISSUE THREAD

**Issue by xiphmont** [AOMediaCodec/av1-spec#169]
7.14.4 of the spec states:

The output variable filterSize is derived as follows:
• If plane is equal to 0, filterSize is set equal to Min( 16, baseSize ),
• Otherwise, (plane is greater than 0), filterSize is set equal to Min( 8, baseSize ).

In the libaom codebase, the correct minimum vales appear to be 14 and 6, not 16 and 8.  Is this an error?

**Comment by ccho111** [comment]
The filterSize in the spec is not the "filter_length" in the codebase. Please check.

**Comment by peterderivaz** [comment]
As ccho111 says, filterLen in the specification is much closer to filter_length in the code.
filterSize in the specification is analogous to the result of get_transform_size  in the code.

filterLen is set to 6 for the special case of chroma.
(In other cases filterLen is left as 16, it would perhaps make more sense for filterLen to be set to 14 here, but as all values above 8 are treated the same, it would not make any difference to the normative behaviour.)

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
