### ISSUE TITLE
8.2.1. Misleading description: "partition size"

### ISSUE THREAD

**Issue by ccho111** [AOMediaCodec/av1-spec#170]
> Aside from the uncompressed header and the partition sizes, the entire bitstream is entropy coded.

What do partition sizes mean ? In VP8 there is syntax for token partition size, but AV1 isn't. So maybe "tile group sizes" is more suitable here?

**Comment by peterderivaz** [comment]
Pull request here:

https://github.com/AOMediaCodec/av1-spec/pull/172

**Comment by peterderivaz** [comment]
The pull request has been merged.
