### ISSUE TITLE
Segmenting AV1

### ISSUE THREAD

**Issue by irrz** [AOMediaCodec/av1-spec#175]
Hello there,
I have managed encoding Raw videos using the FFmpeg to get videos of AV1. 
Now, I wanted to stream them using the MPEG-DASH technique, but it shows me a message that the container is not supported. Hence, I use MP4Box for segmentation

Is there any way I can make the segmentation occurs please?

**Comment by louquillio** [comment]
Sorry, this project is about the AV1 codec's specification document.

You might try the ffmpeg-users list or the #ffmpeg IRC channel.

https://www.ffmpeg.org/contact.html
