### ISSUE TITLE
Unused parameters to some functions and processes

### ISSUE THREAD

**Issue by jackhaughton-argon** [AOMediaCodec/av1-spec#198]
The following functions and processes take parameters which are unused:

- Sec 7.11.3.9 Overlapped motion compensation process - parameters x and y are unused.
- Sec 7.11.3.13 Intra mode variant mask process - parameters plane, x and y are unused. Call to this function also passes extra parameter preds, which is not mentioned in the process section.
- Sec 7.14.3 Filter size process - parameters subX and subY are unused.
- Sec 7.14.6.3 Narrow filter process - parameters limit, blimit, thresh are unused.
- Sec 5.11.41 get_scan() - parameter plane is unused.

**Comment by peterderivaz** [comment]
Done
