### ISSUE TITLE
"TX_SET_INTER_3" column is cut off in the table

### ISSUE THREAD

**Issue by urvangjoshi** [AOMediaCodec/av1-spec#200]
I was looking at the spec here: https://aomediacodec.github.io/av1-spec/av1-spec.pdf

One problem is that the "TX_SET_INTER_3" column is cut off in the table (see section: 6.10.19. Transform type semantics).

The table needs to be formatted so that it fits in page width.

**Comment by louquillio** [comment]
Yes, that will work. Another method is to make a one-off CSS class (`.table-xsm`) that reduces font-size on targeted tables from 16px to 12px. Such tables would end with:

~~~~~
{:.table .table-sm .table-bordered .table-xsm }
~~~~~

Which applies an override in the PDF stylesheet:

~~~~~
// One-off font-size reduction for PDF tables that exceed page width
body
  .table-xsm
    th, td
      font-size: 75%
~~~~~

An example is here (grep for 6.10.19): https://aomediacodec.github.io/av1-spec/av1-spec.pdf

There's not a very clean way to backport either solution to tag v1.0.0 (from which the PDF is currently generated), but there's a v1.1.0 coming up.

Do we have a preference, line-breaks or smaller text?

**Comment by peterderivaz** [comment]
Done
