### ISSUE TITLE
Profile clarification

### ISSUE THREAD

**Issue by dominicsymes** [AOMediaCodec/av1-spec#21]
Hi,

In section "A.1.1 Profiles" the three profiles Main, High and Professional are defined by bullets. A Main profile decoder must decode seq_profile=0, High profile decoder seq_profile=0,1. Professional profile decoder seq_profile=0,1,2. This seems fine to me. However the following Note seems confusing, It says for example that "monochrome is not allowed in high profile". The above bullet has just said that a high profile decoder must support seq_profile=0 and so therefore must support monochrome.

It seems to me it would be clearer to not use the Main, High, Professional terminology (that refers to an increasing sequence of capability) when referring to an individual seq_profile number (such as 0,1,2) which as I understand it are defined so as to have a unique setting for each content type.

So, for example the note could say that monochrome is not permitted when seq_profile=1 rather than not permitted in high profile?

**Comment by peterderivaz** [comment]
Thanks.  I added that note when someone requested it was made more explicit that monochrome is not allowed, but I agree it is incorrect/very confusing the way it is written.  I'll change it to your wording when I am next in the office.

**Comment by peterderivaz** [comment]
I've tried to make the note more correct here:

https://github.com/AOMediaCodec/av1-spec/commit/b63066f713aadcb85e18f3470e38948aab8fba15

**Comment by dominicsymes** [comment]
Thanks Peter - that looks good to me.
