### ISSUE TITLE
Default_Inter_Tx_Type_Set2_Cdf spec/code mismatch

### ISSUE THREAD

**Issue by felixf3** [AOMediaCodec/av1-spec#212]
On Page 423, Default_Inter_Tx_Type_Set2_Cdf is defined as

Default_Inter_Tx_Type_Set2_Cdf[ 13 ] = {
770, 2421, 5225, 12907, 15819, 18927, 21561, 24089, 26595,
28526, 30529, 32768, 0
}

This corresponds to default_inter_ext_tx_cdf defined thus in entropymode.c:

    default_inter_ext_tx_cdf[EXT_TX_SETS_INTER][EXT_TX_SIZES][CDF_SIZE(TX_TYPES)] = {
    ...
      {
          { AOM_CDF12(2731, 5461, 8192, 10923, 13653, 16384, 19115, 21845,
                      24576, 27307, 30037) },
          { AOM_CDF12(2731, 5461, 8192, 10923, 13653, 16384, 19115, 21845,
                      24576, 27307, 30037) },
          { AOM_CDF12(770, 2421, 5225, 12907, 15819, 18927, 21561, 24089, 26595,
                      28526, 30529) },
          { AOM_CDF12(2731, 5461, 8192, 10923, 13653, 16384, 19115, 21845,
                      24576, 27307, 30037) },
      },

The spec definition matches the [][2][] index of the code's array. Are the first, second and fourth entries in the code unused or are they missing from the spec?

**Comment by peterderivaz** [comment]
Yes, I believe these entries in the code are unused.

(If you look at the get_tx_set function, the only way that TX_SET_INTER_2 can be produced is if txSzSqr==TX_16X16 and therefore the second context will always be selected.)

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
