### ISSUE TITLE
Eob_Pt_*_Cdf spec/code mismatche

### ISSUE THREAD

**Issue by felixf3** [AOMediaCodec/av1-spec#213]
Page 437 of the spec:
Default_Eob_Pt_512_Cdf[ COEFF_CDF_Q_CTXS ][ PLANE_TYPES ][ 11 ]
Default_Eob_Pt_1024_Cdf[ COEFF_CDF_Q_CTXS ][ PLANE_TYPES ][ 12 ]

For the above, the reference software (Line 871 of av1/common/token_cdfs.h) uses a matrix that is [ PLANE_TYPES ][2][ 11 ] and [ PLANE_TYPES ][2][ 12 ], respectively. 

Looking at its initialization, the first entry (out of the 2) matches the ones in the spec. 

Can we assume that entry 1 is thus redundant (will never be used)?

This is not related to COEFF_CDF_Q_CTXS: even though the default values have COEFF_CDF_Q_CTXS variants, only 1 is used for encoding; it’s akin to initializing CABAC states with the slice QP.

**Comment by peterderivaz** [comment]
> Can we assume that entry 1 is thus redundant (will never be used)?
Yes, this is intentional - I believe that is impossible for entry 1 to be used in the reference software for a legal bitstream.

**Comment by agrange** [comment]
Issue seems to have been addressed - no action required - so I will close.

Please reopen if there is anything else to consider.
