### ISSUE TITLE
Patent troll warning

### ISSUE THREAD

**Issue by ghost** [AOMediaCodec/av1-spec#285]
Sorry if this is the wrong place to post this, but ive recently seen this link

https://www.streamingmedia.com/Articles/News/Online-Video-News/Sisvel-Launches-Patent-Pools-for-VP9-and-AV1-130840.aspx

where company Sisvel is purported to be charging for license to AV1 product

this is concerning because it appears to be in direct contradiction of this statement:

> AOMedia Video 1 (AV1) is an open, royalty-free video coding format

https://wikipedia.org/wiki/AV1

can someone please clarify - or point me to where a clarification could be found?

**Comment by cup** [comment]
https://github.com/mozilla/aom/issues/9

**Comment by agrange** [comment]
You can find our patent licensing terms here:
https://aomedia.org/license/
