### ISSUE TITLE
DASH Av1 issue

### ISSUE THREAD

**Issue by irrz** [AOMediaCodec/av1-spec#292]
Hi guys
I have encoded .yuv file in different qualities (e.i. different resolutions and bitrates) for Dynamic Adaptive streaming over HTTP.
the command is:
ffmpeg -video_size 3840x2160 -framerate 30 -pixel_format yuv420p10le -y -i Jockey_3840x2160_120fps_420_10bit_YUV_1min.yuv -r 24 -vf scale=256x144 -pix_fmt yuv420p -c:v libaom-av1 -strict experimental -b:v 100K -maxrate 100K Jockey_256x144_100K_VP9.mp4

I replicated the above command for different qulaities.
Then I have dashed them using the dashing command:
MP4Box -dash 1000 -dash-profile onDemand -rap -frag 500 Jockey_256x144_100K_AV1.mp4 Jockey_320x180_200K_AV1.mp4 Jockey_384x216_240K_AV1.mp4 Jockey_384x216_375K_AV1.mp4 Jockey_512x288_550K_AV1.mp4 Jockey_640x360_750K_AV1.mp4 Jockey_768x432_1000K_AV1.mp4 Jockey_1024x576_1500K_AV1.mp4 Jockey_1280x720_3000K_AV1.mp4 Jockey_1280x720_3000K_AV1.mp4 Jockey_1920x1080_4300K_AV1.mp4 Jockey_1920x1080_5800K_AV1.mp4 -mpd-title AV1 -out AV1_1s.mpd

I noticed that the both MP4Client and VLC are not able to adapt the qualities with AV1, although there is higher bandwidth available. I encoded with AVC and HEVC and they were adapting perfectly fine. 
Is there anyway I can apply to ensure the adaptation?

Thanks
Irrz

**Comment by cconcolato** [comment]
This repository is for discussing issues with the AV1 codec specification. For encoding or playback problems, please contact the relevant developers.

**Comment by agrange** [comment]
Not relevant to AV1 specification, so closing.
