### ISSUE TITLE
Experiment using Fast inverse chip z-transform

### ISSUE THREAD

**Issue by LifeIsStrange** [AOMediaCodec/av1-spec#296]
I'm not an expert, but this seems like a major discovery in signal processing! 

From the comments I read:
*Sounds like a pretty awesome milestone to me. So, perhaps in the near future, new compression schemes might allow for reduced mp3 and mp4 file sizes, which means that for the same bandwidth we could see increased resolution/ higher frame rates*

And

*It should be a O(n log n) rather than O(n^2), so the speed increase for large n, which can be common n signal processing, is real.*

Comments:
https://news.ycombinator.com/item?id=21230757
Source:
https://m.techxplore.com/news/2019-10-year-old-puzzle.html

**Comment by agrange** [comment]
Closing - Issue not related to the AV1 spec.
