### ISSUE TITLE
coded video sequence term

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#3]
The term `coded video sequence` is used once in the spec in 6.3 but never defined:
> level specifies the level for the coded video sequence.

It should either be defined or replaced.

**Comment by cconcolato** [comment]
In fact, the term `Temporal unit` which could be used to define a coded video sequence is not used besides for two notes.

**Comment by agrange** [comment]
TU (a single timestamp) seems different to a coded video sequence (usually
multiple timestamps).

**Comment by agrange** [comment]
Maybe you meant "coded video sequence consists on one or more TUs"

**Comment by cconcolato** [comment]
Yes, as written in R18 or R19.

**Comment by peterderivaz** [comment]
There is now a section that defines the term coded video sequence based on the R19 design document:

http://av1-spec.argondesign.com/av1-spec/av1-spec.html#ordering-of-obus
