### ISSUE TITLE
Bitstream conformance for tileWidthSb value

### ISSUE THREAD

**Issue by emirhadi** [AOMediaCodec/av1-spec#305]
In section 6.8.14, page 165 of the spec, it reads:

_tileWidthSb is used to specify the width of each tile in units of superblocks. It is a requirement of bitstream conformance that tileWidthSb is **less than maxTileWidthSb**._

However in another part of the spec (Annex A, page 643), there is this comment:
_• TileWidth * TileHeight is **less than or equal** to 4096 * 2304 for each tile_

These two statements seem to be contradictory.

**Comment by peterderivaz** [comment]
Yes, this was a mistake.  It was fixed a year ago in this commit:

https://github.com/AOMediaCodec/av1-spec/commit/71dfc0d1d6a0c76c375323daa3247a63e2dd5fbb

**Comment by agrange** [comment]
Closing - Issue has been fixed.
