### ISSUE TITLE
frame_offset_update

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#4]
The current spec indicates:
> ``` 
> if (show_frame == 0) {
>        frame_offset_update                      f(5)
>}
>```
and then:
> frame_offset_update specifies how many frames later this frame will be shown.

A frame may never be shown. In that case, what should be the value for frame_offset_update? 0?

**Comment by peterderivaz** [comment]
That is a very good question - I've adjusted the spec to take a particular position (basically that the encoder is free to set any value it wants in this syntax element) but I'll drop an email to the owner of frame_marker Jingning to check that he agrees.

**Comment by cconcolato** [comment]
Spec modified by https://github.com/AOMediaCodec/av1-spec/commit/4e35515a76f9f4639f1db46dc911c65af9b51329

**Comment by peterderivaz** [comment]
Jingning says: "the frame offset value can be completely determined by the encoder, whatever the encoder feels reasonable, the decoder can simply sync with that." so I think the modifications to the specification are correct.
