### ISSUE TITLE
LAST_FRAME and other keywords not defined

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#5]
The constant LAST_FRAME is used in places such as `ref_frame_sign_bias[ LAST_FRAME + i ]` but its value is never defined.

Similar remark for the other keywords: GOLDEN_FRAME, ...

**Comment by jackhaughton-argon** [comment]
LAST_FRAME, GOLDEN_FRAME etc are defined in the semantics for Ref Frames (currently section 6.8.19).

**Comment by cconcolato** [comment]
I saw that section 6.8.19 but it did not seem so clear that this was a definition because  LAST_FRAME is present twice in the table for RefFrame[0] and RefFrame[1]. I read it as follows: if RefFrame[0] = 0, then the reference frame was LAST_FRAME, whatever that meant, and I expected to find the definition of LAST_FRAME somewhere else. 

One way to avoid that confusion is to have only one table.
