### ISSUE TITLE
Luma average rounding in 7.10.4 "Predict Chroma From Luma Process"

### ISSUE THREAD

**Issue by barrbrain** [AOMediaCodec/av1-spec#51]
The description of `lumaAvg` has only a plain right shift.
`lumaAvg >>= Tx_Width_Log2[ txSz ] + Tx_Height_Log2[ txSz ]`
However, in libaom this shift includes rounding.
`lumaAvg = Round2( lumaAvg, Tx_Width_Log2[ txSz ] + Tx_Height_Log2[ txSz ]  )`

**Comment by peterderivaz** [comment]
Thanks for finding and fixing this!
