### ISSUE TITLE
Link to specification goes via Outlook

### ISSUE THREAD

**Issue by edent** [AOMediaCodec/av1-spec#55]
On your website - https://aomedia.org/av1-bitstream-and-decoding-process-specification/

The link to the specification is `https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faomediacodec.github.io%2Fav1-spec%2Fav1-spec.pdf&data=04%7C01%7Cgfrost%40microsoft.com%7Cc01143f4353e426231d508d590e3a9c1%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C1%7C636574229902920663%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&sdata=lLQibtMygoLH30UNXZcUZGAA1i%2FqNE%2Ff6fgotaX3uhI%3D&reserved=0`

That link seems to be a copy & paste from Gabe Frost's email account. 

I think it should point directly to https://aomediacodec.github.io/av1-spec/av1-spec.pdf

**Comment by peterderivaz** [comment]
Thanks, fixed
