### ISSUE TITLE
change the suffix from _obu to _obp

### ISSUE THREAD

**Issue by totang** [AOMediaCodec/av1-spec#57]
The obu includes the  header and payload . Then change the suffix from _obu to _obp(open bitstream playload) is more accurate .

**Comment by peterderivaz** [comment]
I've been asked not to change this.

There was some discussion, but in the end the slight preference was to leave it as it is (partly because several design documents use the current naming scheme, and partly because it is more in line with ITU  codec naming schemes)

**Comment by totang** [comment]
==>and partly because it is more in line with ITU codec naming schemes)
This is absolute wrong . ITU codec naming scheme uses NAL_unit and and suffix  _rbsp (raw_byte_sequence_payload) which clear identify it is payload .
