### ISSUE TITLE
add "disable_deblocking" flag in sequence header 

### ISSUE THREAD

**Issue by totang** [AOMediaCodec/av1-spec#58]
now,we must specify specified value in loop-filter_params() to make the filter don't change the pixels indeed then "disable" deblocking alternative .

And change the loop-filter to deblocking is more accurate . as general loop-filter should include (deblocking+cdef+LR)

**Comment by peterderivaz** [comment]
Is this a feature request that would result in changes to the reference code?

If you want to make a feature request that affects the code, you should post to the aomedia issue tracker:
https://bugs.chromium.org/p/aomedia/issues/list

**Comment by totang** [comment]
Yes ,should change the reference code .

**Comment by peterderivaz** [comment]
Issue moved to aom issue tracker:

https://bugs.chromium.org/p/aomedia/issues/detail?id=1696&q=
