### ISSUE TITLE
restrict  the min_tile_width if "in-loop-filtering" is enable 

### ISSUE THREAD

**Issue by totang** [AOMediaCodec/av1-spec#59]
This can help alleviating  memory latency issue  in case load/store some top buffers into external memory .
The min_tile_width  can be 256 pixels if "in-loop-filtering " is enable .
otherwise min_tile_width   can equal to SB size .

**Comment by peterderivaz** [comment]
Is this a feature request that would result in changes to the reference code?

If you want to make a feature request that affects the code, you should post to the aomedia issue tracker:
https://bugs.chromium.org/p/aomedia/issues/list

**Comment by totang** [comment]
No,just add restriction in specification .

**Comment by peterderivaz** [comment]
Restrictions in the specification should correspond to parts of the code that trigger errors/warning messages.  Can you point out the bit of the code that would result in an error if such a stream was played?

If such an error condition does not currently exist in the code, then the process for adding a new restriction is:
1) Raise issue on the aomedia issue tracker (link above)
2) If agreed, submit code patch to generate an error on streams that fail the spec
3) Then update the spec to match the code

This spec is just based on reverse engineering the reference code - just changing the spec by itself has no meaning unless accompanied by changes to the reference code (or an official accepted design document).

**Comment by peterderivaz** [comment]
Issue moved to aom issue tracker:

**Comment by peterderivaz** [comment]
https://bugs.chromium.org/p/aomedia/issues/detail?id=1697
