### ISSUE TITLE
syntax elements in "6.8.28 Token Semantics" seem doesn't  be referenced anywhere

### ISSUE THREAD

**Issue by pengbins** [AOMediaCodec/av1-spec#6]
syntax elements in "6.8.28 Token Semantics" seem doesn't  be referenced anywhere. 
Should it be removed?  or add corresponding syntax?

**Comment by peterderivaz** [comment]
That is a good spot.  With CONFIG_LV_MAP the coefficients are encoded in a very different way and these syntax elements are no longer present.  It also looks like there are some things in transform tree semantics that are no longer present.  I'll fix these up on Monday (and see if there is a more systematic way of running a script to detect any other occurences.) Thanks

**Comment by pengbins** [comment]
OK, I found that the change of "Turn lv_map lv_map_multi on by default" has been accepted.

https://aomedia.googlesource.com/aom/+/2944f9d110cf2ac6da2bc9c0a61e2628b71ace6b
