### ISSUE TITLE
typo in 7.13.5.1

### ISSUE THREAD

**Issue by nv-alan** [AOMediaCodec/av1-spec#61]
May need to change "**else if()**" to only "**if()**".
*************
mask = 0
if ( filterLen >= 4 ) {
    mask |= (Abs( p1 - p0 ) > limitBd)
    mask |= (Abs( q1 - q0 ) > limitBd)
    mask |= (Abs( p0 - q0 ) * 2 + Abs( p1 - q1 ) / 2 > blimitBd)
} **else if** ( filterLen >= 6 ) {
    mask |= (Abs( p2 - p1 ) > limitBd)
    mask |= (Abs( q2 - q1 ) > limitBd)
} **else if** ( filterLen >= 8 ) {
    mask |= (Abs( p3 - p2 ) > limitBd)
    mask |= (Abs( q3 - q2 ) > limitBd)
}

**Comment by peterderivaz** [comment]
Good spot!

Fix here:
https://github.com/AOMediaCodec/av1-spec/commit/85503f742d2b4906d237cd16a162c291edf6a629
