### ISSUE TITLE
Note about differences between KF and IOF is wrong

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-spec#65]
The spec currently says:
> Note: A key frame is different to an intra-only frame even though both only use intra prediction. The difference is that a key frame fully resets the decoding process. For example, for a sequence of frames A, B, C, frame C can use frame A as a reference if B was an intra-only frame - but not if B was a keyframe.

This is more complex than that. The reset of the decoding process is controlled by refresh_frame_flags.

**Comment by cconcolato** [comment]
BTW, there note uses 'keyframe' as a single word. This is the only occurrence in the spec.

**Comment by cconcolato** [comment]
Also, the definitions of key frames and intra-only frames are wrong:
> Key frame
A frame where the decoding process is reset. Key frames, and following frames, are always decodable without access to preceding frames. A key frame only uses intra prediction.

Same reasons as above. The reset is not controlled by the frame type. Additionally, it should probably refer to the definition of 'intra frame'.

> Intra-only frame
A type of intra frame that does not reset the decoding process.

**Comment by peterderivaz** [comment]
I've simplified the wording here to become more correct but less ambitious:

https://github.com/AOMediaCodec/av1-spec/commit/0d8dde068b930c66b88dc9a2016dbb30dedd0d9d
