### ISSUE TITLE
PARTITION_HORZ_4 / VERT_4 outside frame

### ISSUE THREAD

**Issue by olahugosson** [AOMediaCodec/av1-spec#79]
Hi Peter,

I'm wondering if the spec allows for a coded VERT_4 / HORZ_4 partition that is completely outside the frame while the reference decoder doesn't ?

E.g. consider a 24x24 frame, using a VERT_4 partition at the 32x32 level.
The spec then seems to call "decode_block" 4 times, once for each 8x32 partition.
However, the reference decoder seems to call decode_block only 3 times, not coding the rightmost partition.

Is a check missing in the spec to avoid coding partitions completely outside the frame? (such check is already present for the simple 1:2, 2:1 rectangles).

Regards
/Ola

**Comment by peterderivaz** [comment]
Good spot!  I had assumed partition of VERT_4/HORZ_4 was not allowed when it was partially off-screen, but you are right that it is sometimes allowed.  I've pushed up a fix for this.
