### ISSUE TITLE
Spec for loop filter

### ISSUE THREAD

**Issue by chengchen-google** [AOMediaCodec/av1-spec#87]
I found several problems in spec related to loop filter:

[1]. 6.7.9  If primary_ref_frame is equal to PRIMARY_REF_NONE, loop_filter_delta_enabled should also be set to 1.

[2]. 5.9.12. if ( delta_lf_abs == DELTA_LF_SMALL )  --> if ( delta_lf_abs >= DELTA_LF_SMALL ) 

[3]. 6.9.12. If delta_lf_abs is **larger or** equal to DELTA_LF_SMALL, the value is encoded using delta_lf_rem_bits and delta_lf_abs_bits.

[4]. 7.13.1: Logic of applyFilter is not correct.
Should be:
Otherwise, if (isBlockEdge is equal to 1 or skip is equal to 0 or prevSkip is equal to 0) **and** (current block filter level is not 0 or prev block filter level is not 0), applyFilter is set equal to 1.

[5]. 7.13.2: filterSize is not correct.
Should be:
If plane is equal to 0, filterSize is set equal to Min( **14**, baseSize ),
Otherwise, (plane is greater than 0), filterSize is set equal to Min( **6**, baseSize ).

[6]. Need to update loop filter advance step size.
Loop filter now doesn’t use a fix step of unit of 4x4. Instead, step size depends on tx size.
For example, if current block tx size is TX_8X4, filtering is in pass 0 (filtering vertical edges), then the step is tx_size_wide_unit[TX_8X4], equal to 2 unit 4x4 step size. Similarly, for pass 1, step is tx_size_high_unit[TX_8X4], equal to 1 unit 4x4 step size.

**Comment by peterderivaz** [comment]
1) If primary_ref_frame is equal to PRIMARY_REF_NONE, loop_filter_delta_enabled is set equal to 1 in setup_past_independence

2) I believe it is impossible for the case delta_lf_abs > DELTA_LF_SMALL to occur so this change is unnecessary

3) I believe it is impossible for delta_lf_abs to be larger than DELTA_LF_SMALL so this change is unnecessary

4) The filter is only applied if lvl is greater than zero, so I believe these extra conditions are unnecessary

5) filterSize corresponds to get_transform_size in the code, filterLen corresponds to filter_length, so get_transform_size equal to TX_8X8 corresponds to filterSize equal to 8,  and filterLen equal to 6 (when plane>0)

6) I believe this is just an implementation detail, the intermediate edges will have isTxEdge equal to 0 so will not be filtered

**Comment by chengchen-google** [comment]
2 and 3. Why is delta_lf impossible to be larger than DELTA_LF_SMALL?

**Comment by peterderivaz** [comment]
See the definition of the Cdf:

Default_Delta_Lf_Cdf[ DELTA_LF_SMALL + 2 ] = {
  28160, 32120, 32677, 32768, 0
}

I believe this means that the syntax element delta_lf_abs can only decode as 0,1,2,3.
