### ISSUE TITLE
Independent tiles and context clear

### ISSUE THREAD

**Issue by dominicsymes** [AOMediaCodec/av1-spec#9]
In section 5.8.1 there is the text:

if ( !dependent_tiles || 
         (TileCol == 0 && !AllowDependentTileRow[ TileRow ]) ) {
        clear_above_context( )
    }

I was just wondering why the context is cleared on every column if dependent_tiles==0 but only on column 0 for allow dependent tiles=0.

**Comment by peterderivaz** [comment]
I think it would also be correct if we added the TileCol==0 check into the first case, but I was trying to emphasize that all context is cleared before the tile is decoded (when dependent_tiles==0).

When dependent_tiles!=0, the check for TileCol==0 is important to handle the following case.

Suppose we have 4 tiles in the image in a 2x2 grid and dependent_tiles==1:
A B
C D
When we are decoding tile B we must not call clear_above_context or it will clear all the things written by tile A that are needed by tile C.

**Comment by dominicsymes** [comment]
Thanks Peter for explaining - that makes perfect sense and I see the point in emphasizing it now. (I had not thought above the ABCD case you mention following a forced independent row).
