### ISSUE TITLE
TM_PRED name should be replaced by PAETH_PRED

### ISSUE THREAD

**Issue by urvangjoshi** [AOMediaCodec/av1-spec#91]
This includes "FILTER_TM_PRED" changed to "FILTER_PAETH_PRED" as well.

This will ensure that this new PAETH_PRED mode is not confused with a different TM_PRED mode in VP9, and will also match the name used in the reference encoder/decoder.

**Comment by peterderivaz** [comment]
Do you know what PAETH stands for?

**Comment by urvangjoshi** [comment]
The technique is due to Alan W. Paeth, also used in PNG: https://www.w3.org/TR/PNG-Filters.html
