### ISSUE TITLE
CDEF skip for sub 8x8 blocks

### ISSUE THREAD

**Issue by olahugosson** [AOMediaCodec/av1-spec#94]
Hi Peter,

It seems that "7.14.1 CDEF Block Process" specifies that the CDEF processing for the 8x8 block at (r,c) should be skipped if the Skips[r][c] is set (i.e. if the top-left 4x4 in the 8x8 is skip).

However, it appears that the reference decoder loops over all 4x4 blocks in the 8x8, and only if all 4 are skip, the CDEF for the 8x8 is skipped (see is_8x8_block_skip()).

I think this might be a spec bug?

Regards
/Ola

**Comment by peterderivaz** [comment]
Good spot, I guess the line:
    The variable skip is set equal to Skips[ r ][ c ]
should be replaced by something more like:
   The variable skip is set equal to Skips[ r ][ c ] && Skips[ r +1 ][ c ] && Skips[ r ][ c + 1 ] && Skips[ r + 1 ][ c + 1 ]

Does this match your understanding?

**Comment by olahugosson** [comment]
Yes, that's how I read the code.
