### ISSUE TITLE
"Page [x] of [y]" count at bottoms of pages is quirky

### ISSUE THREAD

**Issue by DeeDeeG** [AOMediaCodec/av1-spec#95]
Expected:

- Page-numbering scheme should start from "Page 1".
- On the last page, numbers should match.

Here's what I'm seeing:

- "Page [x] of [y]" count starts with "Page 0", and goes up from there. 
  - (Non-techies might find this confusing, and I think it defies expectations.)
- Last page says "Page 636 of 647"

**Comment by DeeDeeG** [comment]
A suggestion for ergonomics' sake: I like when a PDF's **bottom-of-page numbering** stay consistent with **the numbering of the PDF file**, as opposed to where the page labeled as "Page 1" of the document is the 24th page of the PDF, or similar. (That way, you can use your PDF browser to jump to a page number (consistent with the labels at the bottom of the page) and actually end up where you expect.)

Maybe you can keep printing the page counts at the bottoms of pages, starting past the table of contents, for style reasons, like you're already doing... But offset the bottom-of-page numbering to match the actual PDF page number for that page. So that would entail beginning the bottom-of-page numbering at "Page 11 of *y*", rather than "Page 0 of *y*", looking at the current PDF* 

As a side-effect, if you do count up from 11, the bottom page would be correctly numbered: 647 is the actual PDF page number of the last page, even though it is currently labeled as "Page 636 of 647"

*(current PDF I am referring to is: https://aomediacodec.github.io/av1-spec/av1-spec.pdf, _"Last modified: 2018-04-17 12:27 PT"_)

**Comment by louquillio** [comment]
Hi, and thanks for the catch. PR #100 cleans this up, for the most part.

The particular combination of Jekyll (for HTML generation) and Prince (for PDF transform from HTML) causes some strange behavior wrt the built-in CSS counters `page` and `pages` and how they're affected by the `counter-reset` and `counter-increment` properties. Briefly, `counter-reset: page` resets to `0`, but a subsequent `counter-increment: page` forces a blank page before "Scope" and causes "Scope" to be numbered "Page 2." Annoying.

The hackish solution is to instead decrement `page` and `pages` by 10 immediately before "Scope" (`counter-increment: page -10 pages -10`). This attains the desired result of "Scope" being "Page 1 of 640" and the last page being 640 of 640.

Wrt syncing PDF page numbering with a PDF reader app's concept of page count, we'll take this under advisement for now. While the PDF page numbering should certainly be sane, it's likeliest that the canonical spec will not be a PDF, rather an HTML document served from aomedia.org -- so there'd be no page numbering going forward. Should this change, we'll reconsider more sophisticated PDF page numbering.

Thanks for your interest!

**Comment by DeeDeeG** [comment]
Just a minor comment, but the page count starts at "Page 2 of *x*" now.

I guess the table of contents is longer than before, or something like that, so the hard-coded offset is off? In any case, it's less jarring starting at two than starting at zero.

Regards,

\- DeeDeeG

**Comment by louquillio** [comment]
Yes, something like that. Fixed by PR #120 .
