### ISSUE TITLE
Sub 8x8 inter prediction for chroma

### ISSUE THREAD

**Issue by dominicsymes** [AOMediaCodec/av1-spec#96]
Hello,

I would like to clarify a point on the sub-8x8 inter prediction. My understanding from the code is that if an 8x8 luma block is split into four 4x4 luma blocks and the last block is inter but not all blocks are inter then the corresponding 4x4 chroma block is inter coded using a single motion vector from the last luma inter block. If all blocks are inter coded the the chroma inter prediction uses four 2x2 inter predictions.

In the specification section 5.9.32, residual(), there is a loop that sets a variable someUseIntra if any of the blocks are detected as intra which I think is for implementing the condition as described above. However, this loop iterates over ( r = 0; r < num4x4H; r++ ) and ( c = 0; c < num4x4W; c++ ) where as far as I can tell num4x4H=num4x4W=1. So this only seems to look at the top left block r=c=0 rather than all four blocks. Please can you clarify if this loop should really iterate r=0,1 and c=0,1. Thanks.

**Comment by peterderivaz** [comment]
Thanks Dominic, you are quite right and the loop should be over more cases.  I've pushed up a proposed fix above.  Do you think this is better?

Note that in 4:2:2 format we only check two blocks, so the loop depends on the subsampling.

Also note that this case can trigger for 16*4 blocks, not just 8x8 blocks.

(For reference, this code corresponds to the computation of sub8x8_inter in common/reconinter.c)

**Comment by dominicsymes** [comment]
Thanks for posting a fix - this looks correct as far as I can see. Perhaps though you could add brackets around the shift left expressions such as "num4x4H << subY" - I think it is easier to read if the order is clear rather than relying on << being a closer binding than < (though don't think that affects correctness).
