### ISSUE TITLE
dynamic range after column transform (iwht case)

### ISSUE THREAD

**Issue by brayden-cnm** [AOMediaCodec/av1-spec#97]
I have a problem between AV1 spec. and reference code about iwht4x4 case.

1) AV1 spec is described as below.

> "Between the row and column transforms, Residual[ i ][ j ] is set equal to Clip3( - ( 1 << (colClampRange - 1 ) ), ( 1 << (colClampRange - 1 ) ) - 1, Residual[ i ][ j ] ) for i = 0..(h-1), for j = 0..(w-1)."

2) AV1 Reference Code

static INLINE tran_high_t check_range(tran_high_t input, int bd) {
  // AV1 TX case
  // - 8 bit: signed 16 bit integer
  // - 10 bit: signed 18 bit integer
  // - 12 bit: signed 20 bit integer
  // - max quantization error = 1828 << (bd - 8)
  const int32_t int_max = (1 << (7 + bd)) - 1 + (914 << (bd - 7));
  const int32_t int_min = -int_max - 1;
#if CONFIG_COEFFICIENT_RANGE_CHECKING
  assert(int_min <= input);
  assert(input <= int_max);
#endif  // CONFIG_COEFFICIENT_RANGE_CHECKING
  return (tran_high_t)clamp64(input, int_min, int_max);
}

What is the maximum bit width for the coeffs between row and column transform in the case of iwht4x4 ?

**Comment by peterderivaz** [comment]
Thanks for posting this: I have raised your issue on the AOM working group and Google is investigating to determine the correct behaviour.

**Comment by peterderivaz** [comment]
The specification has been tightened to restrict the maximum bit width for iwht4x4

https://bugs.chromium.org/p/aomedia/issues/detail?id=1871
