### ISSUE TITLE
Probably a typo is present in the AV1 specification (section 5.9.22)

### ISSUE THREAD

**Issue by slavah264** [AOMediaCodec/av1-spec#98]
at the section 5.9.22. "Inter Block Mode Info Syntax", there is written the following: 
... 
new_mv 
if ( new_mv == 0 ) 
{ YMode = NEWMV 
... 

it seems that '0' should be replaced with '1' as follows:

 new_mv 
if ( new_mv == 1 )
 { YMode = NEWMV

**Comment by slavah264** [comment]
In the code, in the fucntion 'read_inter_mode' the following statement is present:

  is_newmv = aom_read_symbol(r, ec_ctx->newmv_cdf[mode_ctx], 2, ACCT_STR) == 0;
  if (is_newmv) return NEWMV; 

So, if new_mv is non-zero then YMode should have been equal to NEWMV, however the spec. states vice versa

**Comment by peterderivaz** [comment]
The confusion here is that in the code there is an syntax element read using the newmv_cdf tables (so the specification calls the syntax element newmv) that is used to produce a variable is_newmv that is true when the syntax element is equal to 0.

In other words, the code could be rewritten as:

newmv = aom_read_symbol(r, ec_ctx->newmv_cdf[mode_ctx], 2, ACCT_STR);
is_newmv = newmv==0

Does this make it clearer why the spec matches the code?

**Comment by slavah264** [comment]
Thanks

Now it's clear.
